# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('date', models.DateTimeField(verbose_name='date submitted')),
                ('text', models.TextField()),
                ('post_type', models.URLField(choices=[('AP', 'Article Post'), ('VP', 'Video Post'), ('PP', 'Photo Post'), ('SP', 'Slideshow Post')], default='AP', max_length=2)),
                ('url', models.URLField(default=None)),
            ],
        ),
    ]
