# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AP', 'Article Post'), ('VP', 'Video Post'), ('PP', 'Photo Post'), ('SP', 'Slideshow Post')], default='AP', max_length=2),
        ),
    ]
