# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160311_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=140),
        ),
    ]
