# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160311_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='sub_date',
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
