# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20160311_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_type',
            field=models.CharField(choices=[('BR', 'Baltimore Uprising'), ('FP', 'Ferguson Protests'), ('SL', 'Stand With Leah')], default='BR', max_length=2),
        ),
    ]
