# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event_type',
        ),
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.CharField(choices=[('BR', 'Baltimore Uprising'), ('FP', 'Ferguson Protests'), ('SL', 'Stand With Leah'), ('NA', 'Not Currently Trending')], default='BR', max_length=2),
        ),
    ]
